#! /bin/sh

set -e
echo 4096 > /proc/sys/vm/min_free_kbytes
process=agent

case "$1" in
start)
    echo -n "Starting module at process: "
    start-stop-daemon -S -b -a $process
    echo "done"
    ;;
  stop)
    echo -n "Stopping module at process: "
    start-stop-daemon -K -n $process
    echo "done"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage atc_daemon{ start | stop | restart }" >&2
    exit 1
    ;;
esac

. /etc/init.d/start_redtea_keep &

exit 0
