#! /bin/bash

set -e 
flag=1
process=agent

echo "start while..."
while [ $flag -eq 1 ]
do
  echo "start do..."
  pid=`ps -ef | grep $process | grep -v 'grep' | wc -l`;
  echo "start if..."
  if [ $pid -eq 0 ]
  then
      echo "start..."
      start-stop-daemon -S -b -a $process
  else
      echo "runing..."
  fi
  sleep 5s
done


